#!/usr/bin/env python3
"""
Parse a Jira XML (RSS) export into a flat JSON list of ticket dicts.

Usage:
    python parse_jira_xml.py <input.xml> [output.json]

If output.json is omitted, JSON is printed to stdout.

Each ticket dict contains: key, summary, type, status, assignee, reporter,
priority, created, updated, story_points (if present as a custom field named
"Story point estimate" or "Story Points"), sprint (if present), links (list of
"<description> <issue-key>" strings, e.g. "is blocked by DEMO-29755"), and
comments (list of {author, created, text} with HTML stripped).

This script only reads what a single Jira XML export actually contains. Note
that the standard XML/RSS export does NOT include a field-level changelog (no
history of status transitions) -- only the current status plus created/updated
timestamps and comments. Run this once per attached snapshot file when a
sprint has multiple exports attached to the same request; reconstructing a
day-by-day status timeline from the resulting set is covered in
references/status-reconstruction.md in this skill, which uses the snapshot
history first and falls back to timestamp/comment inference only for gaps it
doesn't cover.

Also prints two things to stderr as a side effect: a confirmation of how many
tickets were written, and -- if present -- the export's own generation
timestamp, read from JIRA's leading XML comment ("RSS generated by JIRA ...
at <timestamp>"). That's the real capture time of the export and is what
determines which sprint day this snapshot represents and how multiple
attached snapshots get ordered relative to each other -- see Step 0 of
references/status-reconstruction.md. Never rely on the attachment's filename
or upload order for this.
"""
import sys
import json
import re
import html
import xml.etree.ElementTree as ET


def strip_html(s):
    if s is None:
        return None
    s = html.unescape(s)
    s = re.sub(r"<[^<]+?>", "", s)
    return s.strip()


def text_or_none(el, path):
    found = el.find(path)
    return found.text if found is not None else None


def parse_item(item):
    key = text_or_none(item, "key")
    summary = text_or_none(item, "summary")
    typ = text_or_none(item, "type")
    status = text_or_none(item, "status")
    assignee_el = item.find("assignee")
    assignee = assignee_el.text if assignee_el is not None and assignee_el.text else "Unassigned"
    reporter = text_or_none(item, "reporter")
    priority = text_or_none(item, "priority")
    created = text_or_none(item, "created")
    updated = text_or_none(item, "updated")
    resolution = text_or_none(item, "resolution")

    # story points + sprint live under arbitrary customfield blocks; match by name
    story_points = None
    sprint = None
    for cf in item.findall(".//customfield"):
        name_el = cf.find("customfieldname")
        name = name_el.text if name_el is not None else ""
        if name and "story point" in name.lower():
            val = cf.find(".//customfieldvalue")
            story_points = val.text if val is not None else None
        if name and name.lower() == "sprint":
            val = cf.find(".//customfieldvalue")
            sprint = val.text if val is not None else None

    # issue links: "<description> <issue-key>" e.g. "is blocked by DEMO-29755"
    links = []
    for ilt in item.findall(".//issuelinktype"):
        for outward in ilt.findall("outwardlinks"):
            desc = outward.get("description")
            for ik in outward.findall(".//issuekey"):
                links.append(f"{desc} {ik.text}")
        for inward in ilt.findall("inwardlinks"):
            desc = inward.get("description")
            for ik in inward.findall(".//issuekey"):
                links.append(f"{desc} {ik.text}")

    comments = []
    for c in item.findall(".//comment"):
        comments.append({
            "author": c.get("author"),
            "created": c.get("created"),
            "text": strip_html(c.text),
        })

    return {
        "key": key,
        "summary": summary,
        "type": typ,
        "status": status,
        "assignee": assignee,
        "reporter": reporter,
        "priority": priority,
        "resolution": resolution,
        "story_points": story_points,
        "sprint": sprint,
        "created": created,
        "updated": updated,
        "links": links,
        "comments": comments,
    }


GENERATED_AT_RE = re.compile(r"RSS generated by JIRA.*?\bat\s+(.+?UTC\s+\d{4})")


def find_generated_at(raw_text):
    """Extract JIRA's own export-generation timestamp from the leading XML
    comment, if present (e.g. "Wed Aug 12 12:05:13 UTC 2026"). This is the
    real capture time of the export, used to identify which sprint day this
    snapshot represents and to order multiple attached snapshots relative to
    each other -- see Step 0 of references/status-reconstruction.md. Returns
    the raw matched string, or None if the comment isn't in the expected
    format."""
    m = GENERATED_AT_RE.search(raw_text)
    return m.group(1) if m else None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    in_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(in_path, encoding="utf-8") as f:
        raw_text = f.read()

    root = ET.fromstring(raw_text)
    channel = root.find("channel")
    items = channel.findall("item") if channel is not None else root.findall(".//item")

    data = [parse_item(it) for it in items]

    out = json.dumps(data, indent=2, ensure_ascii=False)
    if out_path:
        with open(out_path, "w") as f:
            f.write(out)
        print(f"Wrote {len(data)} tickets to {out_path}", file=sys.stderr)
    else:
        print(out)

    generated_at = find_generated_at(raw_text)
    if generated_at:
        print(f"Export generated at: {generated_at}", file=sys.stderr)


if __name__ == "__main__":
    main()
